name: unpub_aws
description: A collection of modules to use for deploying unpub into AWS infrastructure.
version: 0.1.0
homepage: https://github.com/bytedance/unpub
publish_to: none
environment:
  sdk: ^3.12.0

dependencies:
  unpub:
  aws_signature_v4:
  aws_common:
  aws_sts_api:
    git:
      url: https://github.com/plentific/aws_client.git
      path: generated/aws_sts_api
      ref: 99afe19f42fc28bef4489d01d1d9d3276899f64a

dev_dependencies:
  lints: ^1.0.0
  test: ^1.17.12
# dependency_overrides:
#   unpub:
#     path: ../unpub
