name: unpub_aws
description: A collection of modules to use for deploying unpub into AWS infrastructure.
version: 0.1.0
homepage: https://github.com/bytedance/unpub
environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  unpub: 
  http: 
  aws_signature_v4:
  aws_common:
  minio: 
    git:
      url: https://github.com/jakubjodelka/minio-dart
    # path: /Users/jakubjodelka/Documents/Programming/Plentific/minio-dart
  aws_sts_api: 
    git:
      url: https://github.com/jakubjodelka/aws_client.git
      path: generated/aws_sts_api
    # path: /Users/jakubjodelka/Documents/Programming/Plentific/aws_client/generated/aws_sts_api

dev_dependencies:
  lints: ^1.0.0
  test: ^1.17.12
  chunked_stream: ^1.4.1
  mockito: ^5.0.16
  build_runner: ^2.1.2
  path: ^1.8.0
  json_annotation: ^4.8.0
# dependency_overrides:
#   unpub:
#     path: ../unpub
