name: unpub
description: Self-hosted private Dart Pub server for Enterprise, with a simple web interface to search and view packages information.
version: 2.0.1-dev.0
homepage: https://github.com/bytedance/unpub
publish_to: none

environment:
  sdk: ^3.12.0
executables:
  unpub: unpub
dependencies:
  args: ^2.7.0
  shelf: ^1.4.2
  shelf_router: ^1.1.4
  http_parser: ^4.1.2
  http: ^1.6.0
  archive: ^4.3.0
  logging: ^1.3.0
  meta: ^1.19.0
  googleapis: ^17.0.0
  yaml: ^3.1.4
  pub_semver: ^2.2.1
  json_annotation: ^4.12.0
  mongo_dart: ^0.10.9
  mime: ^2.1.0
  intl: ^0.20.3
  path: ^1.9.1
  collection: ^1.19.1
  shelf_cors_headers: ^0.1.5
  unpub_aws: 
    path: ../unpub_aws

dev_dependencies:
  test: ^1.32.0
  build_runner: ^2.16.2
  json_serializable: ^6.14.1
  shelf_router_generator: ^1.1.5
  chunked_stream: ^1.4.2
