name: lint
on:
  - push
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: dart:3.12.2
    steps:
      - uses: actions/checkout@v4
      - run: cd unpub && dart pub get --enforce-lockfile && dart analyze
      - run: dart format --set-exit-if-changed unpub unpub_aws
